[package]
name = "offchain"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.7"

anyhow = "1.0"

tokio = { version = "1", features = ["full"] }
tower = "0.4"
tower-http = { version = "0.5", features = ["cors", "trace"]}

serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["fmt", "env-filter"] }

reqwest = { version = "0.12", features = ["json", "multipart", "rustls-tls"] }

dotenvy = "0.15"

ethers = { version = "2", default-features = false, features = ["rustls", "abigen", "contract", "providers", "signers"] }
